### ISSUE TITLE
🐛 BUG: Missing `position.end` for `type: element` AST node since 0.26.0

### ISSUE THREAD

**Issue by bluwy** [withastro/compiler#575]
### What version of `@astrojs/compiler` are you using?

0.27.2

### What package manager are you using?

pnpm

### What operating system are you using?

Mac

### Describe the Bug

For `type: 'element'` AST nodes, the `position` property used to have `start` and `end` props. Since 0.26.0, the `end` prop is missing.

The stackblitz repro has JSON files comparing the AST before and after 0.26.0.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/node-847xhk?file=index.js,result-0.25.2.json

**Comment by Princesseuh** [comment]
This is currently blocking the Prettier plugin. While we generally don't care about positions in AST, this blocks supporting `prettier-ignore` comments as we need to know the original position of the node to print it raw. 

Since it seems like this is related to end tags, perhaps it's related to [the issues we're having in the TSX output](https://github.com/withastro/compiler/issues/571)?
