### ISSUE TITLE
<style> not working on component, if there is no head

### ISSUE THREAD

**Issue by Ambers-AFK** [withastro/compiler#634]
### What version of `astro` are you using?

1.6.7

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

yarn

### What operating system are you using?

Mac

### Describe the Bug

If I write a style inside a Svelte or Vue component it doesn't get applied.

For example:

in Navigation.svelte
```
<script>
    import * as Database from "../../pseudoDB/DB.json";
    const links = Database.links;
</script>

<nav class="navigation-bar">
    {#each links as {name, link}}
        <a class="link" href="{link}"><p>{name}</p></a>
    {/each}
</nav>

<style>
    .navigation-bar {
        display: flex;
        flex-direction: row;
    }
</style>
```

in index.astro
```
---
import Navigation from "../components/Header/Navigation.svelte";
---
<html>
    <body>
        <Navigation client:load/>
    </body>
</html>
```

Only works with `client:load`, if I try to use `client:visible` it doesn't work. And even with `client:load` nothing on style works on build, it only works on dev.

But if I add a `<head>` tag anywhere, it works.

I talked with happydev#6417 on Discord and he told me to post this here.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-yis8pg?file=src/components/Navigation.svelte

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by matthewp** [comment]
Hey @Ambers-AFK, thanks for posting. This is a limitation for how Astro's head rendering works. What it does is wait until it sees the first non-head tag and inserts the links. Since your page doesn't have any non-head tags it doesn't know when to insert them and winds up not inserting them at all.

The best bet is to add a `<body>` tag around your component which will trigger Astro to inject the styles before the body.

Given that the ways to fix this issue would be poorly performant, and the fact that this is an edge case, we're not going to do anything to try and work around the problem at this time, and instead I would just advise you to add a body and/or head tag to your page.
