### ISSUE TITLE
Client side script inside layout file makes html lang attribute disappear

### ISSUE THREAD

**Issue by riccardolardi** [withastro/compiler#660]
### What version of `astro` are you using?

1.6.11

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

yarn

### What operating system are you using?

Mac

### Describe the Bug

It seems using a `<script>` inside the layout which declares the `html` element will make the `lang` attribute disappear.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-xuenvq?file=src/layouts/Layout.astro

### Participation

- [X] I am willing to submit a pull request for this issue.

**Comment by Jarmos-san** [comment]
I've recently stumbled across this bug on [my website](https://jarmos.dev) as well and here's the [source code](https://github.com/Jarmos-san/jarmos.dev/blob/4da0e78353ace8a055f49c5225dc348c24c6e9c8/web/src/layouts/BaseLayout.astro#L40) particularly responsible for generating the base template. Is there any way I can debug and perhaps identify what the root cause of the issue is?

**Comment by skilar** [comment]
Looks like this is caused not just by the `script` tag but also including `styles` before the `html` tag. That should help your issue, @Jarmos-san.

**Comment by Jarmos-san** [comment]
@skilar that fixed the issue! Thanks for it. I'm curious, what was wrong with the code there?

**Comment by skilar** [comment]
I'm not sure what the issue is, @Jarmos-san, seems like there's still a bug in Astro.
