### ISSUE TITLE
🐛 BUG: Generated code imports non-existent function `createMetadata`

### ISSUE THREAD

**Issue by joshamaju** [withastro/compiler#808]
### What version of `@astrojs/compiler` are you using?

1.5.1

### What package manager are you using?

pnpm

### What operating system are you using?

Mac

### Describe the Bug

The generated output when calling the `transform` function contains the below import

```ts
import { createMetadata, createAstro, createComponent, render, maybeRenderHead, renderHead, renderComponent } from "astro/runtime/server/index.js";

const $$metadata = createMetadata("<stdin>", { modules: [], hydratedComponents: [], clientOnlyComponents: [], hydrationDirectives: /* @__PURE__ */ new Set([]), hoisted: [] });
```

but `astro/runtime/server/index.js` doesn't export `createMetadata` and `$$metadata` isn't used anywhere in the generated output.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/vitejs-vite-nuwbp7?file=vite.config.js

**Comment by bluwy** [comment]
The `createMetadata` is only added if the `resolvePath` option is not passed:

https://github.com/withastro/compiler/blob/2157550d113d1325777613600d9915407099eb4b/internal/printer/printer.go#L120-L124

Since Astro always pass the `resolvePath` option, it's provided `astro/runtime/server/index.js` runtime implementation can choose to not export the `createMetadata` API. The change was done in https://github.com/withastro/astro/pull/5133

**Comment by joshamaju** [comment]
Just added a noop

```ts
async resolvePath(specifier) {
    return specifier;
}
```

and it works, strange. Thanks
