### ISSUE TITLE
🐛 BUG: `<body>` tag gets removed when it is a child of a component

### ISSUE THREAD

**Issue by Temez1** [withastro/compiler#935]
### What version of `astro` are you using?

2.0.13

### Are you using an SSR adapter? If so, which one?

No

### What package manager are you using?

npm

### What operating system are you using?

Win 10, WSL 2

### Describe the Bug

Using nested layouts, the body is missing tailwind classes.

```
<Base>
    <body class="bg-black">
        <slot />
    </body>
</Base>
```

Moving `<body class="bg-black">` to base layout fixes the problem.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-txalzk?file=src/layouts/Home.astro

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by natemoo-re** [comment]
We were able to confirm that this is a specific bug with the JS printer in our compiler rather than a parsing bug, which is good news! Should be a fairly straightforward fix when we have a chance to get to it. I'm going to put it on my shortlist.

https://live-astro-compiler.vercel.app/?editor-state=WzMxLDEzOSw4LDAsMTcxLDE0MSwxNTIsMTAxLDIsMywxMDEsMTQ0LDc3LDc1LDE5Niw2NCwxMiwxMzQsMjU1LDc0LDE1MywxMTUsMjE3LDE2MiwzOSw4OSwxNzAsMTc2LDQyLDEzOCwyMjQsNjUsMTgyLDIzNSwxOTksMTYxLDE1MSwxMTYsMzgsMTQ5LDY2LDU4LDQxLDIwMSwyMTIsNjksMTk3LDI1NSwxMTAsMTgyLDIxMywxNzgsMjMyLDEwNSw2MiwyMjIsMzksMTExLDIyMiwyMjgsMjExLDI0OSw4MSw0LDk5LDE4NiwyMjYsMTI2LDIzMiw4LDIyOSw5LDY5LDU5LDE0MiwxMTAsMjM3LDc4LDg2LDEwMywxNzEsODMsMTUxLDU5LDIwNywxLDIzNyw4OSw5NCwxMzAsMjI2LDY5LDI5LDE3OSwxNzIsMTA4LDU2LDE4OCwxMDMsMTU4LDY0LDI0NSwxODgsMTE4LDQ1LDExNSwzLDgyLDE4Nyw3Myw1MCw4MSwxMzcsODMsODYsMjA0LDk2LDExMywzMiwyMzcsOTAsMjIsODMsMTc3LDE1MywyMzcsODksMTk0LDE3OSwxOTIsNDgsOTYsMTEyLDIzNSwyMiw3Miw0OSwxMTksMjUzLDIyMCw5NiwwLDgxLDUyLDEwMCw1OCwzMSw4OCwxODcsNTIsMjI5LDcyLDUwLDI2LDE0Nyw0LDE2MiwxODIsNDQsMjUzLDkzLDc2LDQwLDE3LDIzMiwxMTMsMTIzLDExMSw1MywxMzQsMTgzLDE1MCw1OCw2NiwxMTEsMTQsMTEzLDM2LDIwMiw5Myw1Miw4LDE2OCwyNTEsMTkyLDExMiwyNDMsNzEsODksNjAsNDIsMzAsMTk3LDk5LDE1LDE5NSwxOCw5NywxNDUsNTQsMTU0LDEzMiwxMTEsMjAxLDcwLDE2MiwxNDEsMTg4LDIzNCwyMjAsOTgsODEsMTUsNzUsMiwxNTksMjU0LDE1MSwxMDksODEsNzEsNzQsMTQ5LDEwMywxNTUsMTcxLDE3OCw1LDQ0LDE5Niw5MSwxMzUsMjUxLDEwNyw3Niw5Niw4MSwxOTQsMTIsMTUzLDIzMSwxNDMsMTY2LDcyLDIzMiwxOSwxMzQsMjIxLDE3NSwyMDMsMTQsMjYsMTA3LDU2LDIzNywyNTEsNzIsMTczLDk0LDE0MiwyNTQsMTkxLDE5MCwxLDYsMTUxLDE5MiwxOTIsMTc3LDEsMCwwXQ%3D%3D
